CREATE TABLE PRODUCTS (
PRODUCT_ID VARCHAR2(50) CONSTRAINT PK_PRODUCT_ID PRIMARY KEY,
PRODUCT_NAME VARCHAR2(255),
CATEGORY_ID VARCHAR2(50) NOT NULL,
PRODUCT_PRICE_NUMBER VARCHAR2(255),
PRODUCT_IMAGE VARCHAR2(255),
PRODUCT_AVAIL_QTY VARCHAR2(255),
CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
)


INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAIL_QTY) 
VALUES (00001, 'FRUITTELLA', 00005, 25, 'HELLO', 10)

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (00005, 'CANDY')

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (00001, 'BISCUIT');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (00002, 'BREAD');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (00003, 'SPREAD');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (00004, 'BEVERAGES');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (00006, 'MEAT');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (00007, 'CONDIMENTS');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (00008, 'SPICE');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (00009, 'VEGETABLES');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (00010, 'FRUITS');

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAIL_QTY) 
VALUES (00002, 'OREO', 00001, 25, 'HELLO', 10);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAIL_QTY) 
VALUES (00003, 'GARDENIA', 00002, 25, 'HELLO', 10);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAIL_QTY) 
VALUES (00004, 'NUTELLA', 00003, 25, 'HELLO', 10);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAIL_QTY) 
VALUES (00005, 'PEPSI', 00004, 25, 'HELLO', 10);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAIL_QTY) 
VALUES (00006, 'CHICKEN THIGH', 00006, 25, 'HELLO', 10);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAIL_QTY) 
VALUES (00007, 'KETCHUP', 00007, 25, 'HELLO', 10);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAIL_QTY) 
VALUES (00008, 'CUMIN', 00008, 25, 'HELLO', 10);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAIL_QTY) 
VALUES (00009, 'CABBAGE', 00009, 25, 'HELLO', 10);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAIL_QTY) 
VALUES (00010, 'PINEAPPLE', 00010, 25, 'HELLO', 10);